import {
  AlertTriangleIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  BadgeCheckIcon,
  BellIcon,
  ChartColumnIcon,
  CheckCircleIcon,
  CheckIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronsUpDownIcon,
  ChevronUpIcon,
  CircleIcon,
  CircleXIcon,
  Columns3Icon,
  DownloadIcon,
  EditIcon,
  EyeIcon,
  EyeOffIcon,
  FilterIcon,
  HeartIcon,
  LayoutDashboardIcon,
  LifeBuoyIcon,
  ListOrderedIcon,
  LoaderIcon,
  LogOutIcon,
  MapPinIcon,
  MoonIcon,
  MoreHorizontalIcon,
  PanelLeftOpenIcon,
  PieChartIcon,
  PlusIcon,
  RadioTowerIcon,
  ReceiptIndianRupeeIcon,
  ReceiptTextIcon,
  RefreshCcwDotIcon,
  RepeatIcon,
  SaveIcon,
  SearchIcon,
  SparklesIcon,
  SunIcon,
  TrashIcon,
  UploadIcon,
  UserCheckIcon,
  UserCogIcon,
  UserIcon,
  UsersIcon,
  WifiIcon,
  WifiOffIcon,
  XIcon,
  type Icon,
} from "lucide-react"

export type Icon = typeof Icon
export type IconOptions = keyof typeof Icons

const Icons = {
  AlertTriangle: AlertTriangleIcon,
  ArrowLeft: ArrowLeftIcon,
  MapPin: MapPinIcon,
  Cancel: XIcon,
  ArrowRight: ArrowRightIcon,
  BadgeCheck: BadgeCheckIcon,
  Wifi: WifiIcon,
  WifiOff: WifiOffIcon,
  Bell: BellIcon,
  ChartColumn: ChartColumnIcon,
  Check: CheckIcon,
  CheckCircle: CheckCircleIcon,
  ChevronDown: ChevronDownIcon,
  ChevronLeft: ChevronLeftIcon,
  ChevronRight: ChevronRightIcon,
  ChevronsUpDown: ChevronsUpDownIcon,
  ChevronUp: ChevronUpIcon,
  Circle: CircleIcon,
  CircleX: CircleXIcon,
  Download: DownloadIcon,
  Edit: EditIcon,
  Eye: EyeIcon,
  EyeOff: EyeOffIcon,
  Filter: FilterIcon,
  Heart: HeartIcon,
  LayoutDashboard: LayoutDashboardIcon,
  ListOrdered: ListOrderedIcon,
  LogOut: LogOutIcon,
  Moon: MoonIcon,
  MoreHorizontal: MoreHorizontalIcon,
  PanelLeftOpen: PanelLeftOpenIcon,
  PieChart: PieChartIcon,
  RadioTower: RadioTowerIcon,
  ReceiptIndianRupee: ReceiptIndianRupeeIcon,
  ReceiptText: ReceiptTextIcon,
  RefreshCcwDot: RefreshCcwDotIcon,
  Repeat: RepeatIcon,
  Save: SaveIcon,
  Search: SearchIcon,
  Sparkles: SparklesIcon,
  Sun: SunIcon,
  Trash: TrashIcon,
  UploadIcon: UploadIcon,
  User: UserIcon,
  UserCheck: UserCheckIcon,
  UserCog: UserCogIcon,
  Users: UsersIcon,
  Loader: LoaderIcon,
  Columns3: Columns3Icon,
  Plus: PlusIcon,
  LifeBuoy: LifeBuoyIcon,
}

export default Icons
